name: Generate Artwork Daily
on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:
jobs:
  generate_artwork:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn
      - name: Generate Artwork
        run: yarn generate-artwork
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Publish Artwork"
          git push
